#!/bin/sh
curl $1 -OJ --output-dir ~/Pictures/Wallpaper/ && \
setwp $(find ~/Pictures/Wallpaper/ -regex ".*\.\(jpg\|gif\|png\|jpeg\)" -type f -exec stat -c '%X %n' {} \; | sort -nr | awk 'NR==1,NR==3 {print $2}' | head -n1)
